Repository archethic-foundation/aeweb-cli, pull requests merged in 2023-01, with the labels that each got.

#88 Refactor Aeweb-Cli to Support flatPath Approach
  commands/cli.js
  lib/api.js
  package-lock.json
  package.json
Labels: bug, feature, core team

#92 Fix deploy
  commands/cli.js
Labels: bug

#95 Bug fix
  commands/deploy.js
  lib/api.js
  package-lock.json
Labels: bug

#93 Support of .git folder and .gitignore #82
  commands/cli.js
  commands/deploy.js
  package-lock.json
  package.json
Labels: feature, quality

#96 Add aliases for commands
  commands/deploy.js
  commands/generate_address.js
Labels: feature
